# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'FlashNew' do
  pod 'Masonry'

  # Pods for FlashNew

  target 'FlashNewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlashNewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
